image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.3"
  ANDROID_SDK_TOOLS: "25.2.5"

before_script:
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - chmod +x ./pushremote.sh
  - ./pushremote.sh

stages:
 - release

release:
  stage: release
  script:
   -ls
